name: Day 6 - Build, Deploy, Notify

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull and run container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        docker run -d --name flask-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Wait for app to start
      run: sleep 10

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Validate app is running
      run: curl --fail http://localhost:5000 || exit 1

  notify:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: ${{ secrets.EMAIL_USERNAME }}
        to: pawarsumitp2000@gmail.com
        subject: ✅ Flask App Deployment Success
        body: Your Flask app was deployed successfully on GitHub Runner.
    
